version: "3"

services: 
    web: 
      build: 
        context: .
        # dockerfile: phase1.Dockerfile 
      image: "jacobmeyer/flask"
      environment: 
        - FLASK_ENV=development
      ports: 
        - "5000:5000"

    redis: 
      image: "redis:4.0.11-alpine"